Fixed null meta description error in Product resource
Fixed an exception thrown when meta description is null

TypeError: Cannot assign null to property BigCommerce\ApiV3\ResourceModels\Catalog\Product\Product::$meta_description of type string